disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - function_body_length
  - cyclomatic_complexity
  - trailing_newline
  - vertical_whitespace
  - type_body_length
  - file_length
  - line_length
  - identifier_name
  - opening_brace
  - empty_count
  - mark
  - legacy_constructor
  - function_parameter_count
  - force_cast
  - force_try
  - type_name
  - statement_position
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Life
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Life/External

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone
    - T
identifier_name:
  min_length: 2 # only warning
  excluded: # excluded via string array
    - id
    - URL
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
