# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    changelog_from_git_commits
    
    increment_build_number(xcodeproj: "Life.xcodeproj")
    commit_version_bump(xcodeproj: "Life.xcodeproj")

    sync_code_signing(type: "appstore")
    build_app(workspace: "Life.xcworkspace", scheme: "Life")

    upload_to_testflight

    add_git_tag
    push_to_git_remote
  end
end
